all:
	gcc syn_file_cli.c display.c -std=gnu99 -o syn_file_cli.cgi
	gcc syn_file_ser.c -o syn_file_ser.cgi
#gcc s.c md5.c display.c read_conf.c -std=gnu99 -o ss 
#gcc c.c md5.c display.c read_conf.c -std=gnu99 -o cc

