#!/bin/bash
# dropbear ssh server startup script

. /etc/rc.d/rc.functions

SYNCONF=/usr/local/hawk/ha/sync_config/syn_file_ser

case "$1" in
start)
		$SYNCONF >/dev/null 2>&1 &
		exit 0
	;;
stop)
		killall -9 $SYNCONF
		exit 0
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
